
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          WebExcess.MultiColumn:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        WebExcess.MultiColumn: true
